apiVersion: v1
kind: Service
metadata:
  name: app-svc
# spec:
#   type: NodePort
#   selector:
#     app: myapp
#   ports:
#     - port: 80
#       targetPort: 3000
#       nodePort: 32000
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 3000
     